// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('textChanges', async function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('textChanges', async function() {
    await driver.get("https://volunteercentrecounty.org/volunteering-opportunities")
    await driver.manage().window().setRect({ width: 1440, height: 900 })
    
    // Verify "Filter - Select One" text is present
    const filterText = await driver.findElement(By.css(".mb-\\[8px\\]")).getText()
    assert.strictEqual(filterText, "Filter - Select One", "Filter text should be 'Filter - Select One'")
    
    // Verify title doesn't contain "ALL"
    const titleText = await driver.findElement(By.css(".font-extrabold")).getText()
    assert(!titleText.includes("ALL"), "Title should not contain the word 'ALL'")
  })

  // Verify specific element doesn't contain "ALL"
  const donationText = await driver.findElement(By.css("p.font-Montserrat.font-extrabold")).getText()
  assert(!donationText.includes("ALL"), "Donation text should not contain the word 'ALL'")
})
